env:
  global:
  - secure: TIwj3550lbMmcIW3tPxa1Rm41EEALJXEjWLZ6a1kxJq4yjUPlOZrJN+jnjl0OIox/ihAHBuxKRtonJJ0h2ccawykcypG7Qqoqsq7w1iyBO+rk017OmQ62NBEDHdqPzG6WTYBo6tFbIL8qJ1GvFcNRlk1rC4DWTiFysJukU5v5ZN1nDsRYRXxQLduvfsuONn2HuTvgAYXIfwC8SPA1gqiXYSdAuSUuL/VxcbLH0hBOQzfVGKVSfVMcINuhQA5WuIRVkFNvqc38qrQesPt8ZKYm/21ireajR6z6f/bC7v1RpXdqPGu2vJ6MKuya+l6/Xoy3BZpml/IBKitux2OgaffF6lacj/u1gw7LF/585wwbhE1FfPF5mDLzbV+ca3iTxUGK+aI4Iv2tMn0mtrxJGwuvqqjSdHX+020JidQgObMvSzxEnKKMFvrpmDh3E5tgYPkIPJnavUjsi1G7VaSVyAm6Vc64WgyyJivjsJh+fu3HS36lRjiWjGrqJF++2o/sIS4zOw/lG9Z0MLcjgPJ935phhO59f7ZAEAdV/GV4rT7grG5h8WFWpS3DSBdw7OzhEN+SGDUuZhKhXLf3X2OgqQ6B5LqsbVRvabuX/wip92KgawW7MkWR98VxpnPpskST0Tz8RFwopsvWfuXKizMo+4dD2ON8IIvMz1ZEXBxmwEcRfA=
  - secure: qw4GsYYdD/ESEZcJaEr+8dmE08xbNhqRrGx0pzw7OwTowrLNZDO3dPicSUhF5nil7d/zUV0k0NsVgnuAih2aaWAzjqn2p3hvbEyMx+g/r+ZXfBGueDC+7N00RlMjLZ1YERgXDT7HfeKVGK9aW15OKPLgvL9lVQItJ10rxYKq+Gj6yUZDDJCV1V+WppHUgub8nfD2nCjuEtqu+tWinTHwLZt/BsFHTq5n6CHwvrRHU7ubeVtx/NZo/dQjgv67pcd0oCKkz/EOjXuzyvbV14snAuSgQMv0EpA6wyOB0xDm0yjNnz6lDrnIRgcvo9uBFbfUZ8VG65/IO+fXfhcEHhasQ4MWaeFWtkMM4vtz85omo2MAawxR8s3R8mZqoSaKdXLufpjZGcw/+zxYHYvWtzVjVtjmpaTjwaKappWQ5DtpsYTWOlqMpvD9viVwR1QHastUsS48rbpFYv4C6VJvy4oyeZpxPUMOiyXDPAouHYkipTqYeh9t7GuEOh7Y0JeouV0Xpj3KEqcHDZrF3T0M8TUXkV4bF1HRnXKA5GFrI9bmrOeLkytPI8Go/0Om3wS97hIT1CZtVp104Y1bbhGDUrpLJG1YFfRI+I3FXykhu+Fj0vHV5kJG693+BvnqJy9hmeJQqT70VwG/HEpWMqbhAAprYGe7WnEUjkjIrkwfNzz2f0I=
  - REPO=p1hub/auth.protocol.one
sudo: true
services:
- docker
jobs:
  include:
  - stage: Building image with auth.protocol.one
    script:
    - export TAG=`if [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo
      $TRAVIS_TAG; fi`
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build -t $REPO:$TAG -t $REPO:0.0.$TRAVIS_BUILD_NUMBER .
    - docker push $REPO
notifications:
  email: false
  slack:
    secure: luvQtJzpx/EP/BLKNPEED9fOJM7DISXgTmiN05WUerkSJiCPswphuuKNHDQOZMu0M9qVS6bXYsSOfcziCY4Oq+Beqm79dm1fr7LxicVC8l4ZriyuccjHWSGdPFNvBlcE0/dFv3Nmv+m1/XF7DdsSnwsLaKg1bR2iFAxtHazl1sOZGrkxJ93585JZ16UYrl2jPO/pZZvhfytHuTRbIivcv4rqtPay92KSh5SAzMrTBbglBdh21sGSWp+/lyuj/3An9FaBKiUgdanuxs66xfKJLJW7rNyyO8Q5x1x4zBQofS4PrYFKxVvvTyaQ9HDcg85ZsESUD4xfk8GzUUTKAmMlVnNj7F//gGOhoXnyE7ciCJfO18kpgqr5YATB7/sk9V3lukCqffmvcBzeDHZdIUoiUUz1tBNzxjy00Uqh7hM3xfzv2353KmqCt31zVkTyv9pYo14X3sKY5K1ZN/VmHtSWcsAHtMWVxdsHeeu6tFcsVG6+xbirwXh+DDGqsRgG/CtS+Ile0cludXrUXW2uo5IW1sgau32Jx6ovtY/u48j6UroP9iAadW/lQ/LmNqTCyzTkXXN4YTSOOWTLkM4Zu4N1K1NOwr3QyrRY272FD2xRtIWVbdP7NTJ9zodql5YkxhbvzXyAs7Tr5BJOqNyE/JB2tmRVEEZ+RpeLe63xYzaBH+U=
    
