version: '3'
services:
    php:
        build: .
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"

    nginx:
        container_name: p1-auth-nginx
        image: nginx:1.15.4
        ports:
            - "180:80"
            - "1443:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
        depends_on:
            - "php"

    mongodb:
        image: mongo:4.1.3
        container_name: p1-auth-mongo
        restart: always
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27017"

    redis:
        container_name: p1-auth-redis
        image: redis:3.2
        ports:
            - "16379:6379"

volumes:
  mongodata:
    external: true

