version: '3'
services:
    p1-auth-php:
        build: .
        container_name: p1-auth-php
        networks: 
          - p1devnet
        restart: always

    p1-auth-nginx:
        container_name: p1-auth-nginx
        image: nginx:1.15.4
        networks: 
          - p1devnet
        ports:
            - "8001:80"
            - "8002:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./public/:/app/public/"
        depends_on:
            - "p1-auth-php"

    p1-auth-mongo:
        image: mongo:4.1.3
        container_name: p1-auth-mongo
        restart: always
        networks: 
          - p1devnet
        volumes:
            - p1-auth-mongo:/data/db
        ports:
            - "8003:27017"

    p1-auth-redis:
        container_name: p1-auth-redis
        image: redis:3.2
        networks: 
          - p1devnet
        ports:
            - "8004:6379"

volumes:
  p1-auth-mongo:
    external: true

networks:
  p1devnet:
    external: true